default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/crate-ci/typos
    rev: v1.24.1
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/ruff-pre-commit # python lint + format
    rev: v0.6.2
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
        stages: [pre-commit, pre-push]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
    # all the stuff after this comment is slow, so it is ran only on pushes
  - repo: local
    hooks:
      # it is important to run this hook before pyright, to sync the venv
      - id: python-deps
        name: Install python deps
        stages: [pre-push]
        types: [python, pyi, jupyter]
        entry: uv sync
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/RobertCraigie/pyright-python # python typecheck, on push only
    rev: v1.1.377
    hooks:
      - id: pyright
        stages: [pre-push]
        types_or: [python, pyi, jupyter]
