default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/crate-ci/typos
    rev: v1.26.0
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/ruff-pre-commit # python lint + format
    rev: v0.7.0
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter, toml]
        args: [--fix]
        stages: [pre-commit, pre-push]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: local # python typecheck, on push only
    hooks:
      - id: pyright
        name: Pyright
        stages: [pre-push]
        types_or: [python, pyi, jupyter]
        entry: sh -c 'uv sync && uv tool install pyright && uv run pyright'
        language: system
        pass_filenames: false
        always_run: true
